name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  compile_tests_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Maven dependencies
        run: |
          mvn install:install-file -Dfile="./libs/gpsUtil.jar" -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion="1.0.0" -Dpackaging=jar
          mvn install:install-file -Dfile="./libs/tripPricer.jar" -DgroupId=tripPricer -DartifactId=tripPricer -Dversion="1.0.0" -Dpackaging=jar
          mvn install:install-file -Dfile="./libs/rewardCentral.jar" -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion="1.0.0" -Dpackaging=jar

      - name: Compile
        run: mvn -f ./pom.xml clean compile

      - name: Test
        run: mvn -f ./pom.xml verify -Dskip-tests-performance=false

      - name: Build
        run: mvn -f ./pom.xml "-Dmaven.test.skip=true" package

      - run: mkdir ./staging && cp ./target/*.jar ./staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
